#! /usr/bin/python

# @file
#  This file is part of PUML
#
#  For conditions of distribution and use, please see the copyright
#  notice in the file 'COPYING' at the root directory of this package
#  and the copyright notice at https://github.com/TUM-I5/PUML
# 
# @copyright 2013 Technische Universitaet Muenchen
# @author Sebastian Rettenberger <rettenbs@in.tum.de>
#

import os

Import('env')

env.testSourceFiles.extend(
    [os.path.abspath('NetcdfPum.t.h'),  # Must be the first
     os.path.abspath('NetcdfGroup.t.h'),
     os.path.abspath('NetcdfEntity.t.h')]
  )

Export('env')